/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.Graphics;
import java.awt.Image;
import javax.annotation.Resource;
import static utils.utils.tk;

/**
 *
 * @author ASUS
 */
public class menuPanel extends javax.swing.JPanel {

    /**
     * Creates new form menuPanel
     */
    Image background,title, player1, player2, exit, hd;
    public menuPanel() {
        initComponents();
        background = tk.getImage(Resource.class.getResource("/Images/background.jpg"));
        title = tk.getImage(Resource.class.getResource("/Images/title.png"));
        player1 = tk.getImage(Resource.class.getResource("/Images/1player.png"));
        player2 = tk.getImage(Resource.class.getResource("/Images/2player.png"));
        exit = tk.getImage(Resource.class.getResource("/Images/exit.gif"));
        hd = tk.getImage(Resource.class.getResource("/Images/hd.png"));
        
        this.setSize(800, 600);
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    repaint();
                }
            }
        }).start();
    }
    
    public void drawBackground(Graphics g) {
        g.drawImage(background, 0, 0, 800, 600, null);
    }

    public void drawTitle(Graphics g) {
        g.drawImage(title, 300, 70, 200, 80, null);
    }
    public void drawButton(Graphics g)
    {
        g.drawImage(player1, 460, 200,150,45, null);
//        g.drawRect(460, 200, 150, 45);
        g.drawImage(player2, 460, 260,150,45, null);
        g.drawImage(exit, 480, 320,80,50, null);
        g.drawImage(hd, 250, 470,300,60, null);
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.

        drawBackground(g);
        drawTitle(g);
        drawButton(g);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
